### ISSUE TITLE
Linux: Newly created file not returning contents

### ISSUE THREAD

**Issue by yobert** [bazil/bolt-mount#1]
It seems that fuse on linux will now truncate read results to the filesize reported for a file node.

```
$ bolt-mount fs.db mnt/
$ mkdir mnt/things
$ echo test >mnt/things/file
$ cat mnt/things/file
(returns nothing)
```

**Comment by yobert** [comment]
Ah, I think the problem is some sort of caching.  It's not doing another lookup when you try to cat the newly created file.  If I unmount and then remount, it works.

**Comment by tv42** [comment]
Yeah, I'm seeing this too. Sorry for the delay, working on it now.

**Comment by yobert** [comment]
Looks great! Unrelated: Are you going to gophercon 2015? I'd love to chat with you about this project. Also github needs a way to send a PM.

**Comment by tv42** [comment]
@yobert Most likely yes for Gophercon.
